### ISSUE TITLE
Question about the archtecture and input size

### ISSUE THREAD

**Issue by wangtingwei1993** [bbrattoli/JigsawPuzzlePytorch#8]
I checked the architecture of the official implementation. It seems that your implementation has the same architecture as the official implementation. I think they use the patch size 75*75 as your implementation, rather than 64*64 declared in the paper.  I want to know whether I make some mistakes. ThX

**Comment by bbrattoli** [comment]
If I remember well, the patch size is, as you said, 75x75, but then a 64x64 crop is extracted from the 75x75. So, at the end, the input to the network is 64x64. Let me know if this does not match. Thanks.

**Comment by wangtingwei1993** [comment]
Think about this question: If you use the same architecture as the official implementation. Why you need to resize the patches from 64x64 to 75x75.
I also attach a code block of the official implementation here. It seems that the patch size is 75x75.

name: "CaffeNet"
layer {
  name: "data_0"
  type: "Data"
  top: "data_0"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: false
    crop_size: 255
    mean_value: 104
    mean_value: 117
    mean_value: 123
    siamese_size: 9
    patch_size: 75
    jitter_size: 0
  }
  data_param {
    source: "./imagenet_res_256_256/train"
    batch_size: 256
    backend: LMDB
  }
}

**Comment by bbrattoli** [comment]
Now I see what you mean, I misunderstood the question. You are right, when I created this code there was some ambiguity regarding the input size which I also discussed with the author of the paper. If I remember well, I simply decided to use the size given in the paper, but it should be easy to change that and try both.

**Comment by wangtingwei1993** [comment]
Thanks for your reply.
