### ISSUE TITLE
I don't know why this code doesn't work

### ISSUE THREAD

**Issue by CreamNuts** [bbrattoli/JigsawPuzzlePytorch#9]
To operate the code, you have not touched anything except minor path modifications, but the learning is not going on. What should I do to solve this? This is [my modifed code link](https://github.com/CreamNuts/JigsawPuzzlePytorch)

![image](https://user-images.githubusercontent.com/57064520/76836364-0f469380-6874-11ea-9904-b40b2ce41ce8.png)

**Comment by naoryossiCartica** [comment]
I faced the same problem. set lr=0.01, it will work.

**Comment by CreamNuts** [comment]
> I faced the same problem. set lr=0.01, it will work.

I've already tried it, but it doesn't work. I used lr=0.1, 0.01, 0.001....

**Comment by naoryossiCartica** [comment]
Weird. I went over the entire pipeline and the code is OK. It should work, unless you changed something. How big is your dataset, and how long did you let it run before stopping?

**Comment by CreamNuts** [comment]
> Weird. I went over the entire pipeline and the code is OK. It should work, unless you changed something. How big is your dataset, and how long did you let it run before stopping?

I used ILSVRC-2012 like original code. I just want to test it. And, it didn't start training at least before 4 epochs. After 4 epochs, I stopped the code. So now, I am planning to create and execute a new pipeline based on the original. I can't find what is wrong.

**Comment by naoryossiCartica** [comment]
No, 4 epochs is alot. for me after about 500 iterations of batch size 128 it started learning. Follow the pipeline, see if the weights are changing, see what are the images it tries to learn, see how augmentations affect the learning, and also try at first to simplify the task. try 4 tiles instead of 9. Notice that there are only 24 possible permutations in this case, so you need to create a new permutation file (instead of the 1000 given here ). Good luck

**Comment by CreamNuts** [comment]
> No, 4 epochs is alot. for me after about 500 iterations of batch size 128 it started learning. Follow the pipeline, see if the weights are changing, see what are the images it tries to learn, see how augmentations affect the learning, and also try at first to simplify the task. try 4 tiles instead of 9. Notice that there are only 24 possible permutations in this case, so you need to create a new permutation file (instead of the 1000 given here ). Good luck

Thansk for your advices. I accept your suggestion, and try it.

**Comment by naoryossiCartica** [comment]
PS: Another option is that dataset is very diverse, many different classes. And so it is hard for the net to learn the features. In the original paper they begin the learning process with weights that are not random. Some learning process took place before that.
I suggest that maybe you should start learning the net with one class, and proceed from there .

**Comment by lykim200** [comment]
@CreamNuts Have you had any luck actually getting the network to train? I am running into the same issue where loss and accuracy don't improve.. I am using lr of 0.01, and loss is pretty flat around 6.90 just like in your screenshot. I have trained over 1300 iterations (256 batch size), and this starts to worry me since @naoryossiCartica mentioned that he started learning after about 500 iterations.

**Comment by CreamNuts** [comment]
> @CreamNuts Have you had any luck actually getting the network to train? I am running into the same issue where loss and accuracy don't improve.. I am using lr of 0.01, and loss is pretty flat around 6.90 just like in your screenshot. I have trained over 1300 iterations (256 batch size), and this starts to worry me since @naoryossiCartica mentioned that he started learning after about 500 iterations.

I couldn't train the model. And I lost my interest in this project. Good luck!

**Comment by Aiiiiii** [comment]
> @CreamNuts Have you had any luck actually getting the network to train? I am running into the same issue where loss and accuracy don't improve.. I am using lr of 0.01, and loss is pretty flat around 6.90 just like in your screenshot. I have trained over 1300 iterations (256 batch size), and this starts to worry me since @naoryossiCartica mentioned that he started learning after about 500 iterations.

Hello. Did you solve it?

**Comment by CreamNuts** [comment]
> > @CreamNuts Have you had any luck actually getting the network to train? I am running into the same issue where loss and accuracy don't improve.. I am using lr of 0.01, and loss is pretty flat around 6.90 just like in your screenshot. I have trained over 1300 iterations (256 batch size), and this starts to worry me since @naoryossiCartica mentioned that he started learning after about 500 iterations.
> 
> Hello. Did you solve it?

Unfortunately, I can't solve it.

**Comment by b4shy** [comment]
Changing SGD to ADAM worked for me
